<?php
/**
 * TicketClassAvailability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * TicketClassAvailability Class Doc Comment
 *
 * @category    Class
 * @description The availability if the ticket
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketClassAvailability implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'TicketClass_availability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'date_restrictions_status' => 'bool',
        'date_restrictions_start_date' => 'string',
        'date_restrictions_end_date' => 'string',
        'date_restrictions_start_time' => 'string',
        'date_restrictions_end_time' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'date_restrictions_status' => 'date_restrictions_status',
        'date_restrictions_start_date' => 'date_restrictions_Start_date',
        'date_restrictions_end_date' => 'date_restrictions_end_date',
        'date_restrictions_start_time' => 'date_restrictions_Start_time',
        'date_restrictions_end_time' => 'date_restrictions_end_time'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'date_restrictions_status' => 'setDateRestrictionsStatus',
        'date_restrictions_start_date' => 'setDateRestrictionsStartDate',
        'date_restrictions_end_date' => 'setDateRestrictionsEndDate',
        'date_restrictions_start_time' => 'setDateRestrictionsStartTime',
        'date_restrictions_end_time' => 'setDateRestrictionsEndTime'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'date_restrictions_status' => 'getDateRestrictionsStatus',
        'date_restrictions_start_date' => 'getDateRestrictionsStartDate',
        'date_restrictions_end_date' => 'getDateRestrictionsEndDate',
        'date_restrictions_start_time' => 'getDateRestrictionsStartTime',
        'date_restrictions_end_time' => 'getDateRestrictionsEndTime'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['date_restrictions_status'] = isset($data['date_restrictions_status']) ? $data['date_restrictions_status'] : null;
        $this->container['date_restrictions_start_date'] = isset($data['date_restrictions_start_date']) ? $data['date_restrictions_start_date'] : null;
        $this->container['date_restrictions_end_date'] = isset($data['date_restrictions_end_date']) ? $data['date_restrictions_end_date'] : null;
        $this->container['date_restrictions_start_time'] = isset($data['date_restrictions_start_time']) ? $data['date_restrictions_start_time'] : null;
        $this->container['date_restrictions_end_time'] = isset($data['date_restrictions_end_time']) ? $data['date_restrictions_end_time'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets date_restrictions_status
     * @return bool
     */
    public function getDateRestrictionsStatus()
    {
        return $this->container['date_restrictions_status'];
    }

    /**
     * Sets date_restrictions_status
     * @param bool $date_restrictions_status the scanner code to unlock the event
     * @return $this
     */
    public function setDateRestrictionsStatus($date_restrictions_status)
    {
        $this->container['date_restrictions_status'] = $date_restrictions_status;

        return $this;
    }

    /**
     * Gets date_restrictions_start_date
     * @return string
     */
    public function getDateRestrictionsStartDate()
    {
        return $this->container['date_restrictions_start_date'];
    }

    /**
     * Sets date_restrictions_start_date
     * @param string $date_restrictions_start_date The qunatity of the line item
     * @return $this
     */
    public function setDateRestrictionsStartDate($date_restrictions_start_date)
    {
        $this->container['date_restrictions_start_date'] = $date_restrictions_start_date;

        return $this;
    }

    /**
     * Gets date_restrictions_end_date
     * @return string
     */
    public function getDateRestrictionsEndDate()
    {
        return $this->container['date_restrictions_end_date'];
    }

    /**
     * Sets date_restrictions_end_date
     * @param string $date_restrictions_end_date The price of the line item
     * @return $this
     */
    public function setDateRestrictionsEndDate($date_restrictions_end_date)
    {
        $this->container['date_restrictions_end_date'] = $date_restrictions_end_date;

        return $this;
    }

    /**
     * Gets date_restrictions_start_time
     * @return string
     */
    public function getDateRestrictionsStartTime()
    {
        return $this->container['date_restrictions_start_time'];
    }

    /**
     * Sets date_restrictions_start_time
     * @param string $date_restrictions_start_time The Product's reference id
     * @return $this
     */
    public function setDateRestrictionsStartTime($date_restrictions_start_time)
    {
        $this->container['date_restrictions_start_time'] = $date_restrictions_start_time;

        return $this;
    }

    /**
     * Gets date_restrictions_end_time
     * @return string
     */
    public function getDateRestrictionsEndTime()
    {
        return $this->container['date_restrictions_end_time'];
    }

    /**
     * Sets date_restrictions_end_time
     * @param string $date_restrictions_end_time The Product's reference id
     * @return $this
     */
    public function setDateRestrictionsEndTime($date_restrictions_end_time)
    {
        $this->container['date_restrictions_end_time'] = $date_restrictions_end_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


