<?php
/**
 * CustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerTest Class Doc Comment
 *
 * @category    Class */
// * @description Customer
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Customer"
     */
    public function testCustomer()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "address1"
     */
    public function testPropertyAddress1()
    {

    }

    /**
     * Test attribute "address2"
     */
    public function testPropertyAddress2()
    {

    }

    /**
     * Test attribute "area_code"
     */
    public function testPropertyAreaCode()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "activation_date"
     */
    public function testPropertyActivationDate()
    {

    }

    /**
     * Test attribute "modified_date"
     */
    public function testPropertyModifiedDate()
    {

    }

    /**
     * Test attribute "orders_count"
     */
    public function testPropertyOrdersCount()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "province"
     */
    public function testPropertyProvince()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "signed_up_at"
     */
    public function testPropertySignedUpAt()
    {

    }

    /**
     * Test attribute "time_zone_dst_offset"
     */
    public function testPropertyTimeZoneDstOffset()
    {

    }

    /**
     * Test attribute "time_zone_id"
     */
    public function testPropertyTimeZoneId()
    {

    }

    /**
     * Test attribute "time_zone_raw_offset"
     */
    public function testPropertyTimeZoneRawOffset()
    {

    }

    /**
     * Test attribute "total_spent"
     */
    public function testPropertyTotalSpent()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "valid_phone_number"
     */
    public function testPropertyValidPhoneNumber()
    {

    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {

    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {

    }

}
