<?php
/**
 * EventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EventTest Class Doc Comment
 *
 * @category    Class */
// * @description Event
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Event"
     */
    public function testEvent()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "event_image"
     */
    public function testPropertyEventImage()
    {

    }

    /**
     * Test attribute "event_start_date"
     */
    public function testPropertyEventStartDate()
    {

    }

    /**
     * Test attribute "event_end_date"
     */
    public function testPropertyEventEndDate()
    {

    }

    /**
     * Test attribute "door_open_time"
     */
    public function testPropertyDoorOpenTime()
    {

    }

    /**
     * Test attribute "event_start_time"
     */
    public function testPropertyEventStartTime()
    {

    }

    /**
     * Test attribute "total_capacity"
     */
    public function testPropertyTotalCapacity()
    {

    }

    /**
     * Test attribute "total_tickets_purchased"
     */
    public function testPropertyTotalTicketsPurchased()
    {

    }

    /**
     * Test attribute "purchase_limit"
     */
    public function testPropertyPurchaseLimit()
    {

    }

    /**
     * Test attribute "event_url"
     */
    public function testPropertyEventUrl()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "tickets"
     */
    public function testPropertyTickets()
    {

    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {

    }

    /**
     * Test attribute "artist_name"
     */
    public function testPropertyArtistName()
    {

    }

    /**
     * Test attribute "venue"
     */
    public function testPropertyVenue()
    {

    }

    /**
     * Test attribute "scanner_code"
     */
    public function testPropertyScannerCode()
    {

    }

    /**
     * Test attribute "modified_date"
     */
    public function testPropertyModifiedDate()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

}
