<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class */
// * @description Product
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {

    }

    /**
     * Test attribute "image_source_url"
     */
    public function testPropertyImageSourceUrl()
    {

    }

    /**
     * Test attribute "image_thubnail"
     */
    public function testPropertyImageThubnail()
    {

    }

    /**
     * Test attribute "is_downloadable"
     */
    public function testPropertyIsDownloadable()
    {

    }

    /**
     * Test attribute "is_virtual"
     */
    public function testPropertyIsVirtual()
    {

    }

    /**
     * Test attribute "keyword_locked"
     */
    public function testPropertyKeywordLocked()
    {

    }

    /**
     * Test attribute "out_stock"
     */
    public function testPropertyOutStock()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "price_compare"
     */
    public function testPropertyPriceCompare()
    {

    }

    /**
     * Test attribute "product_tags"
     */
    public function testPropertyProductTags()
    {

    }

    /**
     * Test attribute "published_at"
     */
    public function testPropertyPublishedAt()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "variants"
     */
    public function testPropertyVariants()
    {

    }

    /**
     * Test attribute "vendor"
     */
    public function testPropertyVendor()
    {

    }

}
