<?php
/**
 * ProductVariantsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductVariantsTest Class Doc Comment
 *
 * @category    Class */
// * @description Product variants for a variable type product
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductVariantsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ProductVariants"
     */
    public function testProductVariants()
    {

    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "image_source_url"
     */
    public function testPropertyImageSourceUrl()
    {

    }

    /**
     * Test attribute "in_stock"
     */
    public function testPropertyInStock()
    {

    }

    /**
     * Test attribute "inventory_management"
     */
    public function testPropertyInventoryManagement()
    {

    }

    /**
     * Test attribute "inventory_quantity"
     */
    public function testPropertyInventoryQuantity()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "price_compare"
     */
    public function testPropertyPriceCompare()
    {

    }

    /**
     * Test attribute "product_ref_id"
     */
    public function testPropertyProductRefId()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "taxable"
     */
    public function testPropertyTaxable()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {

    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {

    }

}
