<?php
/**
 * StoreTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StoreTest Class Doc Comment
 *
 * @category    Class */
// * @description Store
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Store"
     */
    public function testStore()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "business_name"
     */
    public function testPropertyBusinessName()
    {

    }

    /**
     * Test attribute "site_url"
     */
    public function testPropertySiteUrl()
    {

    }

    /**
     * Test attribute "terms_of_service"
     */
    public function testPropertyTermsOfService()
    {

    }

    /**
     * Test attribute "modified_date"
     */
    public function testPropertyModifiedDate()
    {

    }

    /**
     * Test attribute "has_integration"
     */
    public function testPropertyHasIntegration()
    {

    }

    /**
     * Test attribute "whitelist_email_on_purchase"
     */
    public function testPropertyWhitelistEmailOnPurchase()
    {

    }

    /**
     * Test attribute "whitelist_popup_on_purchase"
     */
    public function testPropertyWhitelistPopupOnPurchase()
    {

    }

}
