<?php
/**
 * TicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iQX Amplify API Reference
 *
 * Welcome to the iQX Amplify API reference. This is a live example of how you can use [iQX Amplify](http://app.iqxamplify.com/) to integrate your own e-commerce store or ticketing engine.  The iQX Amplify API is organized around the [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer) mothodology, and it uses resource-oriented URLs, and common HTTP response codes to indicate API errors. All requests are authenticated using an `api-key` which can be obtained from your developer dashboard within iQX Amplify.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: development@iqxcorp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TicketTest Class Doc Comment
 *
 * @category    Class */
// * @description Ticket
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Ticket"
     */
    public function testTicket()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "ticket_number"
     */
    public function testPropertyTicketNumber()
    {

    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {

    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {

    }

    /**
     * Test attribute "artist_name"
     */
    public function testPropertyArtistName()
    {

    }

    /**
     * Test attribute "customer_ref_id"
     */
    public function testPropertyCustomerRefId()
    {

    }

    /**
     * Test attribute "venue"
     */
    public function testPropertyVenue()
    {

    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {

    }

    /**
     * Test attribute "ticket_category"
     */
    public function testPropertyTicketCategory()
    {

    }

    /**
     * Test attribute "ticket_price"
     */
    public function testPropertyTicketPrice()
    {

    }

    /**
     * Test attribute "date_purchased"
     */
    public function testPropertyDatePurchased()
    {

    }

    /**
     * Test attribute "door_open_time"
     */
    public function testPropertyDoorOpenTime()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "subtotal_price"
     */
    public function testPropertySubtotalPrice()
    {

    }

    /**
     * Test attribute "total_price"
     */
    public function testPropertyTotalPrice()
    {

    }

    /**
     * Test attribute "total_shipping"
     */
    public function testPropertyTotalShipping()
    {

    }

    /**
     * Test attribute "total_fees"
     */
    public function testPropertyTotalFees()
    {

    }

    /**
     * Test attribute "total_tax"
     */
    public function testPropertyTotalTax()
    {

    }

    /**
     * Test attribute "customer_email"
     */
    public function testPropertyCustomerEmail()
    {

    }

    /**
     * Test attribute "modified_date"
     */
    public function testPropertyModifiedDate()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

}
